ProteinRate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('secretadmin/', admin.site.urls),
    path('', include('protein.urls')),
]

protein/urls.py
from django.urls import path

from . import views

app_name = 'protein'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # # ex: /polls/5/
    path('shakes/<shake_name>/', views.shake, name='shake'),
    # # ex: /polls/5/results/
    path('shakes/', views.shakes, name='shakes'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# ... the rest of your URLconf goes here ...

urlpatterns += staticfiles_urlpatterns()

protein/models.py
import datetime

from django.db import models
from django.utils import timezone

class ProteinShake(models.Model):
    name = models.CharField("Name", max_length=200)
    proteinPercentage = models.DecimalField("g of Protein per 100g", decimal_places=2, max_digits=5)
    creaminess = models.SmallIntegerField("Creaminess")
    solubility = models.SmallIntegerField("Solubility")
    sweetness = models.SmallIntegerField("Sweetness")
    artificiality = models.SmallIntegerField("Artificiality")
    smell = models.SmallIntegerField("Smell")
    taste = models.SmallIntegerField("Taste")

    opinion = models.SmallIntegerField("Personal Opinion")

    review = models.TextField("Review")

    url = models.URLField("Product Page")

    def __str__(self):
        return self.name

#
# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#
#     def __str__(self):
#         return self.question_text
#
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
#
#
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.choice_text

protein/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime
from django.forms import BaseFormSet, formset_factory

from bootstrap4.widgets import RadioSelectButtonGroup

RADIO_CHOICES = (("1", "Radio 1"), ("2", "Radio 2"))


MEDIA_CHOICES = (
    ("Audio", (("vinyl", "Vinyl"), ("cd", "CD"))),
    ("Video", (("vhs", "VHS Tape"), ("dvd", "DVD"))),
    ("unknown", "Unknown"),
)


class TestForm(forms.Form):
    """Form with a variety of widgets to test bootstrap4 rendering."""

    date = forms.DateField(required=False)
    datetime = forms.SplitDateTimeField(widget=AdminSplitDateTime(), required=False)
    subject = forms.CharField(
        max_length=100,
        help_text="my_help_text",
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "placeholdertest"}),
    )
    xss_field = forms.CharField(label='XSS" onmouseover="alert(\'Hello, XSS\')" foo="', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    message = forms.CharField(required=False, help_text="<i>my_help_text</i>")
    sender = forms.EmailField(label="Sender © unicode", help_text='E.g., "me@example.com"')
    secret = forms.CharField(initial=42, widget=forms.HiddenInput)
    cc_myself = forms.BooleanField(
        required=False, help_text='cc stands for "carbon copy." You will get a copy in your mailbox.'
    )
    select1 = forms.ChoiceField(choices=RADIO_CHOICES)
    select2 = forms.MultipleChoiceField(choices=RADIO_CHOICES, help_text="Check as many as you like.")
    select3 = forms.ChoiceField(choices=MEDIA_CHOICES)
    select4 = forms.MultipleChoiceField(choices=MEDIA_CHOICES, help_text="Check as many as you like.")
    category1 = forms.ChoiceField(choices=RADIO_CHOICES, widget=forms.RadioSelect)
    category2 = forms.MultipleChoiceField(
        choices=RADIO_CHOICES, widget=forms.CheckboxSelectMultiple, help_text="Check as many as you like."
    )
    category3 = forms.ChoiceField(widget=forms.RadioSelect, choices=MEDIA_CHOICES)
    category4 = forms.MultipleChoiceField(
        choices=MEDIA_CHOICES, widget=forms.CheckboxSelectMultiple, help_text="Check as many as you like."
    )
    category5 = forms.ChoiceField(widget=RadioSelectButtonGroup, choices=MEDIA_CHOICES)
    addon = forms.CharField(widget=forms.TextInput(attrs={"addon_before": "before", "addon_after": "after"}))

    required_css_class = "bootstrap4-req"

    # Set this to allow tests to work properly in Django 1.10+
    # More information, see issue #337
    use_required_attribute = False

    def clean(self):
        cleaned_data = super().clean()
        raise forms.ValidationError("This error was added to show the non field errors styling.")
        return cleaned_data

protein/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .forms import TestForm

from .models import ProteinShake


def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]

    context = {'form': TestForm()}
    return render(request, 'protein/index.html', context)

def shake(request, shake_name):
    shake = get_object_or_404(ProteinShake, name=shake_name)
    return render(request, 'protein/shake.html', {'shake': shake})

def shakes(request):
    search = ""
    searched = False;
    if request.GET.get('search', False):
        shakes = ProteinShake.objects.filter(name__contains=request.GET.get('search', False)).order_by('opinion')
        search = request.GET.get('search', False)
        searched = True
    else:
        shakes = ProteinShake.objects.order_by('opinion')

    return render(request, 'protein/list.html', {'shakes': shakes, 'searched': searched, 'search': search})
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

protein/templates/protein/base.html
{% extends 'protein/bootstrap.html' %}

{% load bootstrap4 %}

{% block bootstrap4_extra_head %}
    {% load static %}
    <link rel="shortcut icon" href="{%  static 'protein/img/favicon.ico' %}">

    {% block tablejs %}{% endblock %}
    {% block chartjs %}{% endblock %}

{% endblock %}

{% block bootstrap4_content %}



    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'protein:index' %}">Protein Testing</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'protein:shakes' %}">All Shakes <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'protein:shakes' %}">
          <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">


        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>


{% endblock %}

{% block bootstrap4_extra_script %}
{% endblock %}

protein/templates/protein/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}{% endblock %}{% endblock %}

protein/templates/protein/index.html
{% extends 'protein/base.html' %}

{% load bootstrap4 %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <br>
    <h1 class="display-4 text-center html">Prozis Protein Shake Testing</h1>
    <br>
    <p class="text-center">I was gifted over 20 different flavors of protein powder from the popular fitness online store Prozis.</p>
    <p class="text-center">This small webpage is a collection of short reviews of these shakes.</p>
    <p class="text-center">These reviews are probably highly subjective.</p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <p class="text-center">And of course, this site is not, in any ways, affiliated with or sponsored by any named brands.</p>
    <p class="text-center">This page is open source and available at <a href="https://github.com/YellowTech/ProteinRate">Github</a></p>


</script>



{% endblock %}

protein/templates/protein/list.html
{% extends 'protein/base.html' %}

{% load bootstrap4 %}

{% block title %}
    All Shakes
{% endblock %}

{% block tablejs %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'protein/style.css' %}">
    <script src="{% static 'protein/tables.js' %}"></script>
{% endblock %}

{% block content %}
    {% if searched %}
        <br>
        <h1>Search results for "{{ search }}"</h1>
    {% endif %}
    <div class="container">
    <br>
        {% if shakes %}
            <table class="table table-striped sortable">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Personal Opinion</th>
                    <th scope="col">Protein / 100g</th>
                </tr>
                </thead>
                <tbody>
                {% for shake in shakes %}

                    <tr>
                        <td><a href="{% url 'protein:shake' shake.name %}">{{ shake.name }}</a></td>
                        <td>{{ shake.opinion }}</td>
                        <td>{{ shake.proteinPercentage }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No results</p>
        {% endif %}
    </div>




{% endblock %}

protein/templates/protein/shake.html
{% extends 'protein/base.html' %}

{% load bootstrap4 %}

{% block title %}
    {{ shake.name }}
{% endblock %}

{% block chartjs %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <br>
    <h1 class="display-4 text-center html">{{ shake.name }}</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>{{ shake.proteinPercentage }}g Protein / 100g</h3>

                <p>{{ shake.review }}</p>
                <br>

                <h2>Personal Score {{ shake.opinion }}/10</h2>
                <a href="{{ shake.url }}">Product Page</a>
            </div>
            <div class="col">
                <canvas id="myChart{{ shake.id }}" height="250%"></canvas>
                <script>
                    Chart.defaults.global.animation.duration = 2000;
                    var ctx = document.getElementById('myChart{{ shake.id }}');
                    'use strict';
                    var myChart = new Chart(ctx, {
                      "type" : "radar",
                      "data" : {
                        "labels" : ["Creaminess", "Artificiality", "Solubility", "Smell", "Taste", "Sweetness"],
                        "datasets" : [{
                          "data" : [{{ shake.creaminess }}, {{ shake.artificiality }}, {{ shake.solubility }}, {{ shake.smell }}, {{ shake.taste }}, {{ shake.sweetness }}],
                          "fill" : true,
                          "backgroundColor" : "rgba(55,113,174, 0.2)",
                          "borderColor" : "rgb(99,187,255)",
                          "pointBackgroundColor" : "rgb(99,182,255)",
                          "pointBorderColor" : "#323232",
                          "pointHoverBackgroundColor" : "#fff",
                          "pointHoverBorderColor" : "rgb(99,169,255)"
                        }]
                      },
                      "options": {
                        "scale": {
                            "angleLines": {
                                "display": false
                            },
                            "ticks": {
                                "suggestedMin": 0,
                                "suggestedMax": 10
                            }
                        },
                        "legend": {
                          "display": false
                        }
                      }
                    });
                </script>
            </div>
        </div>
    </div>



{% endblock %}